version: '3'

services:
    php:
        build:
            context: ./api
        depends_on:
            - db
            - redis
        links:
            - db
            - redis
        env_file:
            - ./api/.env
        container_name: blynworks-php
        # Comment out these volumes in production
        volumes:
            - ./api:/srv/api:rw
            # If you develop on Linux, comment out the following volumes to just use bind-mounted project directory from host
            - /srv/api/var/
            - /srv/api/var/cache/
            - /srv/api/var/logs/
            - /srv/api/var/sessions/

    api:
        build:
            context: ./api
            dockerfile: ./Dockerfile.nginx
        env_file:
            - ./api/.env
        container_name: blynworks-nginx
        depends_on:
            - php
        links:
            - php
        ports:
            - "8080:80"
            - "8081:443"
        volumes:
            - ./api/public:/srv/api/public:ro

    db:
        # In production, you may want to use a managed database service
        image: mariadb:latest
        env_file:
            - ./api/.env
        container_name: blynworks-mariadb
        volumes:
            - db-data:/var/lib/mysql:rw
            # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
            # - ./docker/db/data:/var/lib/mysql/data:rw
        ports:
            - "23306:3306"
    
    redis:
        image: "redis:alpine"
        env_file:
            - ./api/.env
        container_name: blynkworks-redis
        ports:
            - "6379:6379"

    client:
        # Use a static website hosting service in production
        # See https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#deployment
        build:
            context: ./client
            dockerfile: ./Dockerfile
        env_file:
            - ./client/.env
        container_name: blynworks-client
        volumes:
            - ./client:/usr/src/client:rw
            - /usr/src/client/node_modules
        ports:
            - "3001:3000"

    admin:
        # Use a static website hosting service in production
        # See https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#deployment
        build:
            context: ./admin
            dockerfile: ./Dockerfile
        env_file:
            - ./admin/.env
        container_name: blynworks-admin
        volumes:
            - ./admin:/usr/src/admin:rw
            - /usr/src/admin/node_modules
        ports:
            - "3002:3000"

volumes:
    db-data: {}
