api_platform:
    
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    
    # The title of the API.
    title: Blynkworks API
    
    # The description of the API.
    description: 'Blynkworks API Project'
    
    version: 0.1.0
    
    # Specify a name converter to use.
    name_converter: ~

    # Specify a path name generator to use.
    path_segment_name_generator: 'api_platform.path_segment_name_generator.underscore'

    # Enable the FOSUserBundle integration.
    enable_fos_user: true

    # Enable the Nelmio Api doc integration.
    enable_nelmio_api_doc: false

    # Enable the Swagger documentation and export.
    enable_swagger: true

    # Enable Swagger ui.
    enable_swagger_ui: true

    swagger:
        # The swagger api keys.
        api_keys: []      

    collection:
        # The default order of results.
        order: 'ASC'

        # The name of the query parameter to order results.
        order_parameter_name: 'order'
